### ISSUE TITLE
新版本预计多久能够使用呢？

### ISSUE THREAD

**Issue by CloverAn** [Tryanks/WebTranslator#2]
新版本预计多久能够使用呢？有没有计划时间和新功能的介绍

**Comment by Tryanks** [comment]
已经能够使用，您还需要什么新功能吗？
在计划内的功能是词典模式和 AI 助记模式，下周上线。

**Comment by CloverAn** [comment]
已经可以使用吗？并不是说网站的简版，而是软件呢。似乎并没有看见软件包 @Tryanks

**Comment by CloverAn** [comment]
这是报错了吗？

**Comment by Tryanks** [comment]
页面最底部有两个平台翻译器客户端的下载

**Comment by CloverAn** [comment]
感谢。您这个最好是能加一下背景填充，这半透明很晃眼看不清，翻译量大的时候很遭罪了。

**Comment by Tryanks** [comment]
确实有人反馈有背景半透明的情况，我这边无法复现。可以发一下您系统的相关信息吗

**Comment by Tryanks** [comment]
想起来，您可以通过开启兼容性模式暂缓这个问题。我还是没找到原因在哪里
