### ISSUE TITLE
在 Windows10 系统下运行会出现意料之外的半透明渲染窗口

### ISSUE THREAD

**Issue by CloverAn** [Tryanks/WebTranslator#3]
系统信息：
win10 家庭版 22H2
CPU i7-9750H

**Comment by CloverAn** [comment]
理论上更新补丁到最新，与新版本的差异并不会很大。这种兼容性的确是需要加强一些

**Comment by Tryanks** [comment]
原因：程序中的画笔材质 Mica 在 Windows10 中被替换为 Acrylic。倾向于认为这是上游 Avalonia 的 bug。
暂时的解决方案是在低于 Windows11 的系统版本中关闭画笔材质。
下版本一起上线。

**Comment by CloverAn** [comment]
这个工具主要是做翻译的，为什么会用到画笔呢？不理解其中的用处

**Comment by Tryanks** [comment]
实在抱歉，我不应该在对于一个应用问题的回复中过多提及底层技术细节的内容。
作为对问题本身的回答，以下是相关内容补充：
“画笔”指的是在 Windows 系统下对窗口（Window）渲染过程的管线的种类之一。上文中提到的 Mica（云母材质）、Acrylic（亚克力材质）就是“画笔”的名称。
其中，当窗口渲染的材质选择 Acrylic 时，窗口会表现出如同毛玻璃一般的半透明状态，这也就是您看到的视觉效果。
Mica 材质是我的工具使用的唯一材质（它在 Windows11 中被广泛使用），但由于 Windows10 对最新材质的支持有限，导致窗口被使用错误的渲染管线画出了更大程度的透明度。

**Comment by CloverAn** [comment]
ok，了解了

**Comment by Tryanks** [comment]
在 1ad72d8bcfc1e9a650f8d2f21ebb601161d32a58 中被修复。
稍后可在 Action 页正在进行的自动构建中获得最新版本。
